spring.datasource.url=jdbc:postgresql://ep-holy-voice-a8acpn9c-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jeMyJm5xdG9Q
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=SuperTajnyKluc1234567890abcdefghijklmnopqrstuvwxyzABCDEF==
jwt.expiration=86400000