spring:
datasource:
url: jdbc:postgresql://ep-holy-voice-a8acpn9c-pooler.eastus2.azure.neon.tech/neondb?sslmode=require&channel_binding=require
username: neondb_owner
password: npg_jeMyJm5xdG9Q
driver-class-name: org.postgresql.Driver
jpa:
hibernate:
ddl-auto: update

jwt:
secret: SuperTajnyKluc1234567890abcdefghijklmnopqrstuvwxyzABCDEF==
expiration: 86400000